k: 5
num_epochs: 200
latent_dim: 100
device: "cuda:0"
save_image_epochs: 10
save_image_batch_size: 15
batch_size: 1024
clip_value: 0.01

training:
  discriminator:
    lr: 0.00005
    beta1: 0.5
  generator:
    lr: 0.00005
    beta1: 0.5